server {
  listen 80;

  location /reports/ {
    proxy_pass http://minio:9000/reports/;
    proxy_set_header Host $proxy_host;

    proxy_cache reports_cache;
    proxy_cache_valid 200 30m;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;

    add_header X-Cache-Status $upstream_cache_status always;
  }
}